apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${deploy-name}
    app.kubernetes.io/name: ${app-name}
    app.kubernetes.io/version: v1
  name: ${deploy-name}
  namespace: ${ns-name-prod}
spec:
  ports:
    - name: tcp-80
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: ${deploy-name}
    app.kubernetes.io/name: ${app-name}
    app.kubernetes.io/version: v1
  sessionAffinity: None
  type: ClusterIP
